---
title: "COVID simulation"
output: html_notebook
---

```{r}
source("simulation.R")
library(pracma)
```

Simulation parameters

```{r}
t <- 1:200

# Hospital parameters
beds_per_1000pop <- 5
hospitalisation_rate <- 0.15

parameters_baseline <- c(
  mu = 0, 
  beta = 1.75,
  sigma = 1 / 5, # 1 / mean incubation time?
  gamma = 0.5
)

parameters_distancing <- c(
  mu = 0, 
  beta = 1.75 / 2,
  sigma = 1 / 5, # 1 / mean incubation time?
  gamma = 0.5
)

initials <- c(
  S = 1 - 1/1E4, 
  E = 1/1E3, 
  I = 0, 
  R = 0
)

seir_baseline <- SEIR(
  pars = parameters_baseline, 
  init = initials, 
  time = t
)

seir_distancing <- SEIR(
  pars = parameters_distancing, 
  init = initials, 
  time = t
)
```

```{r}
baseline <- seir_baseline$results %>% 
  mutate(
    needs_hosp = I * hospitalisation_rate,
    treated = pmin(beds_per_1000pop / 1E3, needs_hosp),
    untreated = needs_hosp - treated
  )

distancing <- seir_distancing$results %>% 
  mutate(
    needs_hosp = I * hospitalisation_rate,
    treated = pmin(beds_per_1000pop / 1E3, needs_hosp),
    untreated = needs_hosp - treated
  )

baseline
```

```{r}
distancing
```

```{r, fig.width = 4}
p_data <- bind_rows(
  seir_baseline$results %>% 
    mutate(scenario = "baseline"),
  seir_distancing$results %>% 
    mutate(scenario = "distancing")
)

p <- ggplot(p_data, aes(x = time, y = I, colour = scenario)) +
  geom_line()

p
```

Initialise matrices

```{r}
set.seed(1)
p_size <- 100 * 100

states_baseline <- calc_state_frames(baseline, p_size)
states_baseline
```

```{r}
states_distancing <- calc_state_frames(distancing, p_size)
states_distancing
```


```{r}
matrices <- init_matrices(p_size, nrow = 100, ncol = 100, e0 = states_baseline[1, "E"])
matrices_baseline <- matrices
matrices_distancing <- matrices
```

```{r}
set.seed(5)
plots_base <- gen_sim_plots(
  states_baseline[1:50, ], matrices_baseline, 1, 1E-5, 
  title = "Do nothing"
)
```

```{r}
set.seed(5)
plots_distancing <- gen_sim_plots(
  states_distancing[1:50, ], matrices_distancing, 1, 1E-5, 
  title = "Social distancing"
)
```

```{r}
plots_lines <- gen_line_plots(seir_baseline$results, seir_distancing$results)
```


```{r}
save_frames(plots_base, plots_distancing, plots_lines, break_at = 5)
```

```{r}
gifski::gifski(
  list.files("./png/", pattern = "\\.png$", full.names = TRUE), 
  gif_file = "out2.gif",
  delay = 0.1,
  width = 1000,
  height = 600
)
```

```{r}
p <- plot_frame(matrices_baseline, "Business as usual")
```


```{r}
p <- plot_lines_frame(seir_baseline$results, seir_distancing$results, 20)
p
```

